# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to=b''),
        ),
    ]
